[package]
name = "bf-rs"
version = "0.1.0"
authors = ["Jacob Dillon <jad340@protonmail.com>", "Daniel Shaw <dashaw92@gmail.com"]
edition = "2018"

[lib]
name = "bf"
path = "src/lib.rs"

[[bin]]
name = "bf-rs"
path = "src/main.rs"